---
title: Câbler un potentiomètre
hero_image: images/banner.png
description: Comment câbler un potentiomètre à un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-09"
steps:
  - title: Câbler un potentiomètre
